version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://leonardoxavier:123456@db/healthcare_db
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=leonardoxavier
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=healthcare_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
